### ISSUE TITLE
Error For `pip install .` With macOS ARM64

### ISSUE THREAD

**Issue by YTKme** [NVlabs/flip#35]
**ProductName:** macOS
**ProductVersion:** 14.6.1
**BuildVersion:** 23G93

When following the [Python (API and Tool)](https://github.com/NVlabs/flip/tree/main/python#python-api-and-tool) installation instruction on macOS ARM64, getting a `NameError: name 'extra_link_args' is not defined. Did you mean: 'extra_compile_args'?`

```bash
$ pip install .
Processing /Users/yk/Desktop/Project/Repository/YK/flip/python
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/Users/yk/Desktop/Project/Workspace/Python/pv311-ssca-110-m-1089/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/yk/Desktop/Project/Workspace/Python/pv311-ssca-110-m-1089/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/yk/Desktop/Project/Workspace/Python/pv311-ssca-110-m-1089/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/wd/43c5yw956bb870c0wcwwy21h0000gq/T/pip-build-env-wvv1roqg/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/wd/43c5yw956bb870c0wcwwy21h0000gq/T/pip-build-env-wvv1roqg/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/wd/43c5yw956bb870c0wcwwy21h0000gq/T/pip-build-env-wvv1roqg/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/wd/43c5yw956bb870c0wcwwy21h0000gq/T/pip-build-env-wvv1roqg/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 55, in <module>
      NameError: name 'extra_link_args' is not defined. Did you mean: 'extra_compile_args'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by inversepixel** [comment]
Sorry for the late reply. We currently do not have easy access to macOS to try this. Did you try with `extra_compile_args` and did it work?

**Comment by YTKme** [comment]
can you elaborate a bit on `extra_compile_args`? I tried different `CFLAGS` and `LDFLAGS` when configuring OpenEXR, but not flip. Is there a specific `extra_compile_args` I should use?

**Comment by pandersson94** [comment]
Hi @YTKme,

We found the problem that caused your issues, and have fixed it (and quite a bit more with the new version). Please try installing FLIP through `pip install flip-evaluator`. We've tried and found that it runs successfully on a macOS machine.

Let us know how it goes!

Thanks!

**Comment by YTKme** [comment]
Hi @pandersson94,

This is awesome! I just followed the instruction of installing `flip-evaluator` and tested on macOS Sequoia 15.1 and it work fine! Thank you for the update! (I'll close this for the resolution)

Cheers! 🥂🎉
